[2024-10-21T03:16:34.226+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-21T03:16:34.245+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt.transform_data.run_fact_items_information manual__2024-10-21T03:14:06.911426+00:00 [queued]>
[2024-10-21T03:16:34.252+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt.transform_data.run_fact_items_information manual__2024-10-21T03:14:06.911426+00:00 [queued]>
[2024-10-21T03:16:34.253+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-21T03:16:34.281+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): transform_data.run_fact_items_information> on 2024-10-21 03:14:06.911426+00:00
[2024-10-21T03:16:34.295+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=408) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-21T03:16:34.297+0000] {standard_task_runner.py:72} INFO - Started process 419 to run task
[2024-10-21T03:16:34.296+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt', 'transform_data.run_fact_items_information', 'manual__2024-10-21T03:14:06.911426+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpj0lj766m']
[2024-10-21T03:16:34.299+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask transform_data.run_fact_items_information
[2024-10-21T03:16:37.460+0000] {task_command.py:467} INFO - Running <TaskInstance: elt.transform_data.run_fact_items_information manual__2024-10-21T03:14:06.911426+00:00 [running]> on host 6c3793bbe9c9
[2024-10-21T03:16:37.987+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mherszage' AIRFLOW_CTX_DAG_ID='elt' AIRFLOW_CTX_TASK_ID='transform_data.run_fact_items_information' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T03:14:06.911426+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T03:14:06.911426+00:00'
[2024-10-21T03:16:38.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-21T03:16:38.046+0000] {sql.py:266} INFO - Executing: BEGIN TRANSACTION
;

CREATE TEMPORARY TABLE staging_fact_items_information AS
(
WITH filter_variables AS
(SELECT COALESCE(MAX(_fact_items_information_audit_time), '2024-10-16'::timestamp) AS last_updated FROM "2024_melissa_herszage_schema".l2_fact_items_information)

    SELECT item_id,
           CASE WHEN condition = 'new' THEN 1 ELSE 2 END as condition_id,
           CASE WHEN currency = 'ARS' THEN 1 ELSE 2 END as currency_id,
           price,
           available_quantity,
           created_at as _l1_audit_time,
           current_timestamp as _fact_items_information_audit_time
        FROM "2024_melissa_herszage_schema".l1_item_prices
    )
;

DELETE FROM "2024_melissa_herszage_schema".l2_fact_items_information
WHERE item_id IN (SELECT item_id FROM staging_fact_items_information)
;

INSERT INTO "2024_melissa_herszage_schema".l2_fact_items_information
(SELECT * FROM staging_fact_items_information)
;

END TRANSACTION
;
[2024-10-21T03:16:38.098+0000] {base.py:84} INFO - Retrieving connection 'redshift_default'
[2024-10-21T03:16:39.269+0000] {base.py:84} INFO - Retrieving connection 'redshift_default'
[2024-10-21T03:16:43.887+0000] {sql.py:509} INFO - Running statement: BEGIN TRANSACTION
;

CREATE TEMPORARY TABLE staging_fact_items_information AS
(
WITH filter_variables AS
(SELECT COALESCE(MAX(_fact_items_information_audit_time), '2024-10-16'::timestamp) AS last_updated FROM "2024_melissa_herszage_schema".l2_fact_items_information)

    SELECT item_id,
           CASE WHEN condition = 'new' THEN 1 ELSE 2 END as condition_id,
           CASE WHEN currency = 'ARS' THEN 1 ELSE 2 END as currency_id,
           price,
           available_quantity,
           created_at as _l1_audit_time,
           current_timestamp as _fact_items_information_audit_time
        FROM "2024_melissa_herszage_schema".l1_item_prices
    )
;

DELETE FROM "2024_melissa_herszage_schema".l2_fact_items_information
WHERE item_id IN (SELECT item_id FROM staging_fact_items_information)
;

INSERT INTO "2024_melissa_herszage_schema".l2_fact_items_information
(SELECT * FROM staging_fact_items_information)
;

END TRANSACTION
;, parameters: None
[2024-10-21T03:16:44.461+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1830, in execute
    ps = cache["ps"][key]
         ~~~~~~~~~~~^^^^^
KeyError: ('BEGIN TRANSACTION\n;\n\nCREATE TEMPORARY TABLE staging_fact_items_information AS\n(\nWITH filter_variables AS\n(SELECT COALESCE(MAX(_fact_items_information_audit_time), \'2024-10-16\'::timestamp) AS last_updated FROM "2024_melissa_herszage_schema".l2_fact_items_information)\n\n    SELECT item_id,\n           CASE WHEN condition = \'new\' THEN 1 ELSE 2 END as condition_id,\n           CASE WHEN currency = \'ARS\' THEN 1 ELSE 2 END as currency_id,\n           price,\n           available_quantity,\n           created_at as _l1_audit_time,\n           current_timestamp as _fact_items_information_audit_time\n        FROM "2024_melissa_herszage_schema".l1_item_prices\n    )\n;\n\nDELETE FROM "2024_melissa_herszage_schema".l2_fact_items_information\nWHERE item_id IN (SELECT item_id FROM staging_fact_items_information)\n;\n\nINSERT INTO "2024_melissa_herszage_schema".l2_fact_items_information\n(SELECT * FROM staging_fact_items_information)\n;\n\nEND TRANSACTION\n;', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1911, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2203, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '4303', 'R': 'exec_parse_message'}
[2024-10-21T03:16:44.873+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt, task_id=transform_data.run_fact_items_information, run_id=manual__2024-10-21T03:14:06.911426+00:00, execution_date=20241021T031406, start_date=20241021T031634, end_date=20241021T031644
[2024-10-21T03:16:45.055+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-21T03:16:45.075+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 133 for task transform_data.run_fact_items_information ({'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '4303', 'R': 'exec_parse_message'}; 419)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1830, in execute
    ps = cache["ps"][key]
         ~~~~~~~~~~~^^^^^
KeyError: ('BEGIN TRANSACTION\n;\n\nCREATE TEMPORARY TABLE staging_fact_items_information AS\n(\nWITH filter_variables AS\n(SELECT COALESCE(MAX(_fact_items_information_audit_time), \'2024-10-16\'::timestamp) AS last_updated FROM "2024_melissa_herszage_schema".l2_fact_items_information)\n\n    SELECT item_id,\n           CASE WHEN condition = \'new\' THEN 1 ELSE 2 END as condition_id,\n           CASE WHEN currency = \'ARS\' THEN 1 ELSE 2 END as currency_id,\n           price,\n           available_quantity,\n           created_at as _l1_audit_time,\n           current_timestamp as _fact_items_information_audit_time\n        FROM "2024_melissa_herszage_schema".l1_item_prices\n    )\n;\n\nDELETE FROM "2024_melissa_herszage_schema".l2_fact_items_information\nWHERE item_id IN (SELECT item_id FROM staging_fact_items_information)\n;\n\nINSERT INTO "2024_melissa_herszage_schema".l2_fact_items_information\n(SELECT * FROM staging_fact_items_information)\n;\n\nEND TRANSACTION\n;', ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1911, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2203, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '4303', 'R': 'exec_parse_message'}
[2024-10-21T03:16:45.189+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-21T03:16:46.332+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-21T03:16:46.336+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
