[2024-10-18T05:11:25.008+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T05:11:25.023+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt.transform_data.l2_dim_item manual__2024-10-18T05:09:19.059272+00:00 [queued]>
[2024-10-18T05:11:25.028+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt.transform_data.l2_dim_item manual__2024-10-18T05:09:19.059272+00:00 [queued]>
[2024-10-18T05:11:25.029+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T05:11:25.035+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): transform_data.l2_dim_item> on 2024-10-18 05:09:19.059272+00:00
[2024-10-18T05:11:25.042+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1948) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-18T05:11:25.043+0000] {standard_task_runner.py:72} INFO - Started process 1950 to run task
[2024-10-18T05:11:25.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt', 'transform_data.l2_dim_item', 'manual__2024-10-18T05:09:19.059272+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp9i956tga']
[2024-10-18T05:11:25.047+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask transform_data.l2_dim_item
[2024-10-18T05:11:25.345+0000] {task_command.py:467} INFO - Running <TaskInstance: elt.transform_data.l2_dim_item manual__2024-10-18T05:09:19.059272+00:00 [running]> on host a414d3516fe8
[2024-10-18T05:11:25.423+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mherszage' AIRFLOW_CTX_DAG_ID='elt' AIRFLOW_CTX_TASK_ID='transform_data.l2_dim_item' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T05:09:19.059272+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-18T05:09:19.059272+00:00'
[2024-10-18T05:11:25.424+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T05:11:25.436+0000] {sql.py:266} INFO - Executing: BEGIN TRANSACTION
;

CREATE TEMPORARY TABLE staging_dim_item AS
(
WITH filter_variables AS
(SELECT COALESCE(MAX(_dim_item_audit_time), '2024-10-16'::timestamp) AS last_updated FROM tapi_l2.dim_item)

    SELECT id as item_id,
        title,
        created_at as _l1_audit_time,
        current_timestamp as _dim_item_audit_time
    FROM "2024_melissa_herszage_schema".l1_items as i
    CROSS JOIN filter_variables fv
    WHERE i.updated_at > last_updated
    )
;

DELETE FROM tapi_l2.dim_item
WHERE company_code IN (SELECT item_id FROM staging_dim_item)
;

INSERT INTO tapi_l2.dim_item
(SELECT * FROM staging_dim_item)
;

END TRANSACTION
;
[2024-10-18T05:11:25.441+0000] {base.py:84} INFO - Retrieving connection 'redshift_default'
[2024-10-18T05:11:25.448+0000] {base.py:84} INFO - Retrieving connection 'redshift_default'
[2024-10-18T05:11:26.646+0000] {sql.py:509} INFO - Running statement: BEGIN TRANSACTION
;

CREATE TEMPORARY TABLE staging_dim_item AS
(
WITH filter_variables AS
(SELECT COALESCE(MAX(_dim_item_audit_time), '2024-10-16'::timestamp) AS last_updated FROM tapi_l2.dim_item)

    SELECT id as item_id,
        title,
        created_at as _l1_audit_time,
        current_timestamp as _dim_item_audit_time
    FROM "2024_melissa_herszage_schema".l1_items as i
    CROSS JOIN filter_variables fv
    WHERE i.updated_at > last_updated
    )
;

DELETE FROM tapi_l2.dim_item
WHERE company_code IN (SELECT item_id FROM staging_dim_item)
;

INSERT INTO tapi_l2.dim_item
(SELECT * FROM staging_dim_item)
;

END TRANSACTION
;, parameters: None
[2024-10-18T05:11:26.986+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "tapi_l2" does not exist

[2024-10-18T05:11:27.018+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=elt, task_id=transform_data.l2_dim_item, run_id=manual__2024-10-18T05:09:19.059272+00:00, execution_date=20241018T050919, start_date=20241018T051125, end_date=20241018T051127
[2024-10-18T05:11:27.061+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T05:11:27.062+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 194 for task transform_data.l2_dim_item (schema "tapi_l2" does not exist
; 1950)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "tapi_l2" does not exist

[2024-10-18T05:11:27.093+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-18T05:11:27.150+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T05:11:27.151+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
